/* onvifdiscoveryStub.h
   Generated by gSOAP 2.8.111 for ../../../gsoap-2.8.111/gsoap/import/wsdd10.h

gSOAP XML Web services tools
Copyright (C) 2000-2021, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#define SOAP_WSDD_2005
#define SOAP_WSA_200408
#define SOAP_NAMESPACE_OF_wsa	"http://schemas.xmlsoap.org/ws/2004/08/addressing"
#define SOAP_NAMESPACE_OF_wsdd	"http://schemas.xmlsoap.org/ws/2005/04/discovery"

#ifndef onvifdiscoveryStub_H
#define onvifdiscoveryStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 208111
# error "GSOAP VERSION 208111 MISMATCH IN GENERATED CODE VERSUS LIBRARY CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumeration Types                                                          *
 *                                                                            *
\******************************************************************************/


/* wsa.h:124 */
#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
/* wsa:RelationshipTypeValues */
enum wsa__RelationshipTypeValues {
	wsa__Reply = 0
};
#endif

/* wsa.h:132 */
#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
/* wsa:FaultSubcodeValues */
enum wsa__FaultSubcodeValues {
	wsa__InvalidMessageInformationHeader = 0,
	wsa__MessageInformationHeaderRequired = 1,
	wsa__DestinationUnreachable = 2,
	wsa__ActionNotSupported = 3,
	wsa__EndpointUnavailable = 4
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:109 */
#ifndef SOAP_TYPE_wsdd__FaultCodeType
#define SOAP_TYPE_wsdd__FaultCodeType (58)
/* wsdd:FaultCodeType */
enum wsdd__FaultCodeType {
	wsdd__MatchingRuleNotSupported = 0
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes, Structs and Unions                                                *
 *                                                                            *
\******************************************************************************/

struct wsa__EndpointReferenceType;	/* wsa.h:99 */
struct wsa__ReferencePropertiesType;	/* wsa.h:102 */
struct wsa__ReferenceParametersType;	/* wsa.h:105 */
struct wsa__ServiceNameType;	/* wsa.h:108 */
struct wsa__Relationship;	/* wsa.h:111 */
struct wsdd__HelloType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:64 */
struct wsdd__ByeType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:66 */
struct wsdd__ProbeType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:68 */
struct wsdd__ProbeMatchesType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:70 */
struct wsdd__ProbeMatchType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:72 */
struct wsdd__ResolveType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:74 */
struct wsdd__ResolveMatchesType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:76 */
struct wsdd__ResolveMatchType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:78 */
struct wsdd__SecurityType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:82 */
struct wsdd__SigType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:84 */
struct wsdd__ScopesType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:80 */
struct wsdd__AppSequenceType;	/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:86 */
struct __wsdd__Hello;	/* wsdx.h:67 */
struct __wsdd__Bye;	/* wsdx.h:76 */
struct __wsdd__Probe;	/* wsdx.h:85 */
struct __wsdd__ProbeMatches;	/* wsdx.h:94 */
struct __wsdd__Resolve;	/* wsdx.h:103 */
struct __wsdd__ResolveMatches;	/* wsdx.h:112 */

/* wsa.h:99 */
#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
/* complex XML schema type 'wsa:EndpointReferenceType': */
struct SOAP_CMAC wsa__EndpointReferenceType {
      public:
        /** Required element 'wsa:Address' of XML schema type 'xsd:string' */
        char *Address;
        /** Optional element 'wsa:ReferenceProperties' of XML schema type 'wsa:ReferencePropertiesType' */
        struct wsa__ReferencePropertiesType *ReferenceProperties;
        /** Optional element 'wsa:ReferenceParameters' of XML schema type 'wsa:ReferenceParametersType' */
        struct wsa__ReferenceParametersType *ReferenceParameters;
        /** Optional element 'wsa:PortType' of XML schema type 'xsd:QName' */
        char **PortType;
        /** Optional element 'wsa:ServiceName' of XML schema type 'wsa:ServiceNameType' */
        struct wsa__ServiceNameType *ServiceName;
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
      public:
        /** Return unique type id SOAP_TYPE_wsa__EndpointReferenceType */
        long soap_type() const { return SOAP_TYPE_wsa__EndpointReferenceType; }
        /** Constructor with member initializations */
        wsa__EndpointReferenceType() : Address(), ReferenceProperties(), ReferenceParameters(), PortType(), ServiceName(), __size(), __any(), __anyAttribute() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsa__EndpointReferenceType * SOAP_FMAC2 onvifdiscovery_instantiate_wsa__EndpointReferenceType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsa.h:102 */
#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
/* complex XML schema type 'wsa:ReferencePropertiesType': */
struct SOAP_CMAC wsa__ReferencePropertiesType {
      public:
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
      public:
        /** Return unique type id SOAP_TYPE_wsa__ReferencePropertiesType */
        long soap_type() const { return SOAP_TYPE_wsa__ReferencePropertiesType; }
        /** Constructor with member initializations */
        wsa__ReferencePropertiesType() : __size(), __any() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsa__ReferencePropertiesType * SOAP_FMAC2 onvifdiscovery_instantiate_wsa__ReferencePropertiesType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsa.h:105 */
#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
/* complex XML schema type 'wsa:ReferenceParametersType': */
struct SOAP_CMAC wsa__ReferenceParametersType {
      public:
        /** Sequence of elements '-any' of XML schema type 'xsd:anyType' stored in dynamic array __any of length __size */
        int __size;
        char **__any;
      public:
        /** Return unique type id SOAP_TYPE_wsa__ReferenceParametersType */
        long soap_type() const { return SOAP_TYPE_wsa__ReferenceParametersType; }
        /** Constructor with member initializations */
        wsa__ReferenceParametersType() : __size(), __any() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsa__ReferenceParametersType * SOAP_FMAC2 onvifdiscovery_instantiate_wsa__ReferenceParametersType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsa.h:108 */
#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
/* simple XML schema type 'wsa:ServiceNameType': */
struct SOAP_CMAC wsa__ServiceNameType {
      public:
        /** Simple content of XML schema type 'xsd:QName' wrapped by this struct */
        char *__item;
        /** Optional attribute 'PortName' of XML schema type 'xsd:string' */
        char *PortName;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
      public:
        /** Return unique type id SOAP_TYPE_wsa__ServiceNameType */
        long soap_type() const { return SOAP_TYPE_wsa__ServiceNameType; }
        /** Constructor with member initializations */
        wsa__ServiceNameType() : __item(), PortName(), __anyAttribute() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsa__ServiceNameType * SOAP_FMAC2 onvifdiscovery_instantiate_wsa__ServiceNameType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsa.h:111 */
#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
/* simple XML schema type 'wsa:Relationship': */
struct SOAP_CMAC wsa__Relationship {
      public:
        /** Simple content of XML schema type 'xsd:string' wrapped by this struct */
        char *__item;
        /** Optional attribute 'RelationshipType' of XML schema type 'xsd:QName' */
        char *RelationshipType;
        /** Optional attribute '-anyAttribute' of XML schema type 'xsd:anyType' */
        char *__anyAttribute;
      public:
        /** Return unique type id SOAP_TYPE_wsa__Relationship */
        long soap_type() const { return SOAP_TYPE_wsa__Relationship; }
        /** Constructor with member initializations */
        wsa__Relationship() : __item(), RelationshipType(), __anyAttribute() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsa__Relationship * SOAP_FMAC2 onvifdiscovery_instantiate_wsa__Relationship(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsa.h:255 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
/* SOAP_ENV__Header: */
struct SOAP_CMAC SOAP_ENV__Header {
      public:
        /** Optional element 'wsa:MessageID' of XML schema type 'wsa:MessageID' */
        char *wsa__MessageID;
        /** Optional element 'wsa:RelatesTo' of XML schema type 'wsa:RelatesTo' */
        struct wsa__Relationship *wsa__RelatesTo;
        /** Optional element 'wsa:From' of XML schema type 'wsa:From' */
        struct wsa__EndpointReferenceType *wsa__From;
        /** MustUnderstand */
        struct wsa__EndpointReferenceType *wsa__ReplyTo;
        /** MustUnderstand */
        struct wsa__EndpointReferenceType *wsa__FaultTo;
        /** MustUnderstand */
        char *wsa__To;
        /** MustUnderstand */
        char *wsa__Action;
        /** Optional element 'wsdd:AppSequence' of XML schema type 'wsdd:AppSequenceType' */
        struct wsdd__AppSequenceType *wsdd__AppSequence;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Header */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Header; }
        /** Constructor with member initializations */
        SOAP_ENV__Header() : wsa__MessageID(), wsa__RelatesTo(), wsa__From(), wsa__ReplyTo(), wsa__FaultTo(), wsa__To(), wsa__Action(), wsdd__AppSequence() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Header * SOAP_FMAC2 onvifdiscovery_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* wsa.h:271 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
/* SOAP_ENV__Detail: */
struct SOAP_CMAC SOAP_ENV__Detail {
      public:
        char *__any;
        /** Any type of element 'fault' assigned to fault with its SOAP_TYPE_<typename> assigned to __type */
        /** Do not create a cyclic data structure through this member unless SOAP encoding or SOAP_XML_GRAPH are used for id-ref serialization */
        int __type;
        void *fault;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Detail */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Detail; }
        /** Constructor with member initializations */
        SOAP_ENV__Detail() : __any(), __type(), fault() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Detail * SOAP_FMAC2 onvifdiscovery_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* wsa.h:272 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
/* Type SOAP_ENV__Code is a recursive data type, (in)directly referencing itself through its (base or derived class) members */
/* SOAP_ENV__Code: */
struct SOAP_CMAC SOAP_ENV__Code {
      public:
        /** Optional element 'SOAP-ENV:Value' of XML schema type 'xsd:QName' */
        char *SOAP_ENV__Value;
        /** Optional element 'SOAP-ENV:Subcode' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Subcode;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Code */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Code; }
        /** Constructor with member initializations */
        SOAP_ENV__Code() : SOAP_ENV__Value(), SOAP_ENV__Subcode() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Code * SOAP_FMAC2 onvifdiscovery_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* wsa.h:273 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
/* SOAP_ENV__Reason: */
struct SOAP_CMAC SOAP_ENV__Reason {
      public:
        /** Optional element 'SOAP-ENV:Text' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Text;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Reason */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Reason; }
        /** Constructor with member initializations */
        SOAP_ENV__Reason() : SOAP_ENV__Text() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Reason * SOAP_FMAC2 onvifdiscovery_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* wsa.h:278 */
#ifndef WITH_NOGLOBAL
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
/* SOAP_ENV__Fault: */
struct SOAP_CMAC SOAP_ENV__Fault {
      public:
        /** Optional element 'faultcode' of XML schema type 'xsd:QName' */
        char *faultcode;
        /** Optional element 'faultstring' of XML schema type 'xsd:string' */
        char *faultstring;
        /** Optional element 'faultactor' of XML schema type 'xsd:string' */
        char *faultactor;
        /** Optional element 'detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *detail;
        /** Optional element 'SOAP-ENV:Code' of XML schema type 'SOAP-ENV:Code' */
        struct SOAP_ENV__Code *SOAP_ENV__Code;
        /** Optional element 'SOAP-ENV:Reason' of XML schema type 'SOAP-ENV:Reason' */
        struct SOAP_ENV__Reason *SOAP_ENV__Reason;
        /** Optional element 'SOAP-ENV:Node' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Node;
        /** Optional element 'SOAP-ENV:Role' of XML schema type 'xsd:string' */
        char *SOAP_ENV__Role;
        /** Optional element 'SOAP-ENV:Detail' of XML schema type 'SOAP-ENV:Detail' */
        struct SOAP_ENV__Detail *SOAP_ENV__Detail;
      public:
        /** Return unique type id SOAP_TYPE_SOAP_ENV__Fault */
        long soap_type() const { return SOAP_TYPE_SOAP_ENV__Fault; }
        /** Constructor with member initializations */
        SOAP_ENV__Fault() : faultcode(), faultstring(), faultactor(), detail(), SOAP_ENV__Code(), SOAP_ENV__Reason(), SOAP_ENV__Node(), SOAP_ENV__Role(), SOAP_ENV__Detail() { }
        /** Friend allocator */
        friend SOAP_FMAC1 SOAP_ENV__Fault * SOAP_FMAC2 onvifdiscovery_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
};
#endif
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:64 */
#ifndef SOAP_TYPE_wsdd__HelloType
#define SOAP_TYPE_wsdd__HelloType (43)
/* complex XML schema type 'wsdd:HelloType': */
struct SOAP_CMAC wsdd__HelloType {
      public:
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__HelloType */
        long soap_type() const { return SOAP_TYPE_wsdd__HelloType; }
        /** Constructor with member initializations */
        wsdd__HelloType() : wsa__EndpointReference(), Types(), Scopes(), XAddrs(), MetadataVersion() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__HelloType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__HelloType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:66 */
#ifndef SOAP_TYPE_wsdd__ByeType
#define SOAP_TYPE_wsdd__ByeType (44)
/* complex XML schema type 'wsdd:ByeType': */
struct SOAP_CMAC wsdd__ByeType {
      public:
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Optional element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int *MetadataVersion;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ByeType */
        long soap_type() const { return SOAP_TYPE_wsdd__ByeType; }
        /** Constructor with member initializations */
        wsdd__ByeType() : wsa__EndpointReference(), Types(), Scopes(), XAddrs(), MetadataVersion() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ByeType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ByeType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:68 */
#ifndef SOAP_TYPE_wsdd__ProbeType
#define SOAP_TYPE_wsdd__ProbeType (45)
/* complex XML schema type 'wsdd:ProbeType': */
struct SOAP_CMAC wsdd__ProbeType {
      public:
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ProbeType */
        long soap_type() const { return SOAP_TYPE_wsdd__ProbeType; }
        /** Constructor with member initializations */
        wsdd__ProbeType() : Types(), Scopes() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ProbeType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ProbeType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:70 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchesType
#define SOAP_TYPE_wsdd__ProbeMatchesType (46)
/* complex XML schema type 'wsdd:ProbeMatchesType': */
struct SOAP_CMAC wsdd__ProbeMatchesType {
      public:
        /** Sequence of elements 'wsdd:ProbeMatch' of XML schema type 'wsdd:ProbeMatchType' stored in dynamic array ProbeMatch of length __sizeProbeMatch */
        int __sizeProbeMatch;
        struct wsdd__ProbeMatchType *ProbeMatch;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ProbeMatchesType */
        long soap_type() const { return SOAP_TYPE_wsdd__ProbeMatchesType; }
        /** Constructor with member initializations */
        wsdd__ProbeMatchesType() : __sizeProbeMatch(), ProbeMatch() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ProbeMatchesType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ProbeMatchesType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:72 */
#ifndef SOAP_TYPE_wsdd__ProbeMatchType
#define SOAP_TYPE_wsdd__ProbeMatchType (47)
/* complex XML schema type 'wsdd:ProbeMatchType': */
struct SOAP_CMAC wsdd__ProbeMatchType {
      public:
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ProbeMatchType */
        long soap_type() const { return SOAP_TYPE_wsdd__ProbeMatchType; }
        /** Constructor with member initializations */
        wsdd__ProbeMatchType() : wsa__EndpointReference(), Types(), Scopes(), XAddrs(), MetadataVersion() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ProbeMatchType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ProbeMatchType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:74 */
#ifndef SOAP_TYPE_wsdd__ResolveType
#define SOAP_TYPE_wsdd__ResolveType (48)
/* complex XML schema type 'wsdd:ResolveType': */
struct SOAP_CMAC wsdd__ResolveType {
      public:
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ResolveType */
        long soap_type() const { return SOAP_TYPE_wsdd__ResolveType; }
        /** Constructor with member initializations */
        wsdd__ResolveType() : wsa__EndpointReference() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ResolveType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ResolveType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:76 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchesType
#define SOAP_TYPE_wsdd__ResolveMatchesType (49)
/* complex XML schema type 'wsdd:ResolveMatchesType': */
struct SOAP_CMAC wsdd__ResolveMatchesType {
      public:
        /** Optional element 'wsdd:ResolveMatch' of XML schema type 'wsdd:ResolveMatchType' */
        struct wsdd__ResolveMatchType *ResolveMatch;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ResolveMatchesType */
        long soap_type() const { return SOAP_TYPE_wsdd__ResolveMatchesType; }
        /** Constructor with member initializations */
        wsdd__ResolveMatchesType() : ResolveMatch() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ResolveMatchesType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ResolveMatchesType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:78 */
#ifndef SOAP_TYPE_wsdd__ResolveMatchType
#define SOAP_TYPE_wsdd__ResolveMatchType (50)
/* complex XML schema type 'wsdd:ResolveMatchType': */
struct SOAP_CMAC wsdd__ResolveMatchType {
      public:
        /** Required element 'wsa:EndpointReference' of XML schema type 'wsa:EndpointReference' */
        struct wsa__EndpointReferenceType wsa__EndpointReference;
        /** Optional element 'wsdd:Types' of XML schema type 'xsd:QName' */
        char *Types;
        /** Optional element 'wsdd:Scopes' of XML schema type 'wsdd:ScopesType' */
        struct wsdd__ScopesType *Scopes;
        /** Optional element 'wsdd:XAddrs' of XML schema type 'wsdd:UriListType' */
        char *XAddrs;
        /** Required element 'wsdd:MetadataVersion' of XML schema type 'xsd:unsignedInt' */
        unsigned int MetadataVersion;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ResolveMatchType */
        long soap_type() const { return SOAP_TYPE_wsdd__ResolveMatchType; }
        /** Constructor with member initializations */
        wsdd__ResolveMatchType() : wsa__EndpointReference(), Types(), Scopes(), XAddrs(), MetadataVersion() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ResolveMatchType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ResolveMatchType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:82 */
#ifndef SOAP_TYPE_wsdd__SecurityType
#define SOAP_TYPE_wsdd__SecurityType (52)
/* complex XML schema type 'wsdd:SecurityType': */
struct SOAP_CMAC wsdd__SecurityType {
      public:
        /** Optional element 'wsdd:Sig' of XML schema type 'wsdd:SigType' */
        struct wsdd__SigType *Sig;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__SecurityType */
        long soap_type() const { return SOAP_TYPE_wsdd__SecurityType; }
        /** Constructor with member initializations */
        wsdd__SecurityType() : Sig() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__SecurityType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__SecurityType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:84 */
#ifndef SOAP_TYPE_wsdd__SigType
#define SOAP_TYPE_wsdd__SigType (53)
/* complex XML schema type 'wsdd:SigType': */
struct SOAP_CMAC wsdd__SigType {
      public:
        /** Required attribute 'Scheme' of XML schema type 'xsd:string' */
        char *Scheme;
        /** Optional attribute 'KeyId' of XML schema type 'xsd:string' */
        char *KeyId;
        /** Required attribute 'Refs' of XML schema type 'xsd:string' */
        char *Refs;
        /** Required attribute 'Sig' of XML schema type 'xsd:string' */
        char *Sig;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__SigType */
        long soap_type() const { return SOAP_TYPE_wsdd__SigType; }
        /** Constructor with member initializations */
        wsdd__SigType() : Scheme(), KeyId(), Refs(), Sig() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__SigType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__SigType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:80 */
#ifndef SOAP_TYPE_wsdd__ScopesType
#define SOAP_TYPE_wsdd__ScopesType (51)
/* simple XML schema type 'wsdd:ScopesType': */
struct SOAP_CMAC wsdd__ScopesType {
      public:
        /** Simple content of XML schema type 'wsdd:UriListType' wrapped by this struct */
        char *__item;
        /** Optional attribute 'MatchBy' of XML schema type 'xsd:string' */
        char *MatchBy;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__ScopesType */
        long soap_type() const { return SOAP_TYPE_wsdd__ScopesType; }
        /** Constructor with member initializations */
        wsdd__ScopesType() : __item(), MatchBy() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__ScopesType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__ScopesType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:86 */
#ifndef SOAP_TYPE_wsdd__AppSequenceType
#define SOAP_TYPE_wsdd__AppSequenceType (54)
/* complex XML schema type 'wsdd:AppSequenceType': */
struct SOAP_CMAC wsdd__AppSequenceType {
      public:
        /** Required attribute 'InstanceId' of XML schema type 'xsd:unsignedInt' */
        unsigned int InstanceId;
        /** Optional attribute 'SequenceId' of XML schema type 'xsd:string' */
        char *SequenceId;
        /** Required attribute 'MessageNumber' of XML schema type 'xsd:unsignedInt' */
        unsigned int MessageNumber;
      public:
        /** Return unique type id SOAP_TYPE_wsdd__AppSequenceType */
        long soap_type() const { return SOAP_TYPE_wsdd__AppSequenceType; }
        /** Constructor with member initializations */
        wsdd__AppSequenceType() : InstanceId(), SequenceId(), MessageNumber() { }
        /** Friend allocator */
        friend SOAP_FMAC1 wsdd__AppSequenceType * SOAP_FMAC2 onvifdiscovery_instantiate_wsdd__AppSequenceType(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:67 */
#ifndef SOAP_TYPE___wsdd__Hello
#define SOAP_TYPE___wsdd__Hello (82)
/* Wrapper: */
struct SOAP_CMAC __wsdd__Hello {
      public:
        /** Optional element 'wsdd:Hello' of XML schema type 'wsdd:HelloType' */
        struct wsdd__HelloType *wsdd__Hello;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__Hello */
        long soap_type() const { return SOAP_TYPE___wsdd__Hello; }
        /** Constructor with member initializations */
        __wsdd__Hello() : wsdd__Hello() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__Hello * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__Hello(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:76 */
#ifndef SOAP_TYPE___wsdd__Bye
#define SOAP_TYPE___wsdd__Bye (85)
/* Wrapper: */
struct SOAP_CMAC __wsdd__Bye {
      public:
        /** Optional element 'wsdd:Bye' of XML schema type 'wsdd:ByeType' */
        struct wsdd__ByeType *wsdd__Bye;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__Bye */
        long soap_type() const { return SOAP_TYPE___wsdd__Bye; }
        /** Constructor with member initializations */
        __wsdd__Bye() : wsdd__Bye() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__Bye * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__Bye(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:85 */
#ifndef SOAP_TYPE___wsdd__Probe
#define SOAP_TYPE___wsdd__Probe (88)
/* Wrapper: */
struct SOAP_CMAC __wsdd__Probe {
      public:
        /** Optional element 'wsdd:Probe' of XML schema type 'wsdd:ProbeType' */
        struct wsdd__ProbeType *wsdd__Probe;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__Probe */
        long soap_type() const { return SOAP_TYPE___wsdd__Probe; }
        /** Constructor with member initializations */
        __wsdd__Probe() : wsdd__Probe() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__Probe * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__Probe(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:94 */
#ifndef SOAP_TYPE___wsdd__ProbeMatches
#define SOAP_TYPE___wsdd__ProbeMatches (91)
/* Wrapper: */
struct SOAP_CMAC __wsdd__ProbeMatches {
      public:
        /** Optional element 'wsdd:ProbeMatches' of XML schema type 'wsdd:ProbeMatchesType' */
        struct wsdd__ProbeMatchesType *wsdd__ProbeMatches;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__ProbeMatches */
        long soap_type() const { return SOAP_TYPE___wsdd__ProbeMatches; }
        /** Constructor with member initializations */
        __wsdd__ProbeMatches() : wsdd__ProbeMatches() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__ProbeMatches * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__ProbeMatches(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:103 */
#ifndef SOAP_TYPE___wsdd__Resolve
#define SOAP_TYPE___wsdd__Resolve (94)
/* Wrapper: */
struct SOAP_CMAC __wsdd__Resolve {
      public:
        /** Optional element 'wsdd:Resolve' of XML schema type 'wsdd:ResolveType' */
        struct wsdd__ResolveType *wsdd__Resolve;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__Resolve */
        long soap_type() const { return SOAP_TYPE___wsdd__Resolve; }
        /** Constructor with member initializations */
        __wsdd__Resolve() : wsdd__Resolve() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__Resolve * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__Resolve(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/* wsdx.h:112 */
#ifndef SOAP_TYPE___wsdd__ResolveMatches
#define SOAP_TYPE___wsdd__ResolveMatches (97)
/* Wrapper: */
struct SOAP_CMAC __wsdd__ResolveMatches {
      public:
        /** Optional element 'wsdd:ResolveMatches' of XML schema type 'wsdd:ResolveMatchesType' */
        struct wsdd__ResolveMatchesType *wsdd__ResolveMatches;
      public:
        /** Return unique type id SOAP_TYPE___wsdd__ResolveMatches */
        long soap_type() const { return SOAP_TYPE___wsdd__ResolveMatches; }
        /** Constructor with member initializations */
        __wsdd__ResolveMatches() : wsdd__ResolveMatches() { }
        /** Friend allocator */
        friend SOAP_FMAC1 __wsdd__ResolveMatches * SOAP_FMAC2 onvifdiscovery_instantiate___wsdd__ResolveMatches(struct soap*, int, const char*, const char*, size_t*);
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/


/* (built-in):0 */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
typedef char *_XML;
#endif

/* (built-in):0 */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
typedef char *_QName;
#endif

/* wsa.h:225 */
#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
typedef struct wsa__EndpointReferenceType _wsa__EndpointReference;
#endif

/* wsa.h:228 */
#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
typedef char *_wsa__MessageID;
#endif

/* wsa.h:231 */
#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
typedef struct wsa__Relationship _wsa__RelatesTo;
#endif

/* wsa.h:234 */
#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
typedef char *_wsa__To;
#endif

/* wsa.h:237 */
#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
typedef char *_wsa__Action;
#endif

/* wsa.h:240 */
#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
typedef struct wsa__EndpointReferenceType _wsa__From;
#endif

/* wsa.h:243 */
#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
typedef struct wsa__EndpointReferenceType _wsa__ReplyTo;
#endif

/* wsa.h:246 */
#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
typedef struct wsa__EndpointReferenceType _wsa__FaultTo;
#endif

/* wsa.h:249 */
#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
typedef unsigned int _wsa__ReplyAfter;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:97 */
#ifndef SOAP_TYPE_wsdd__QNameListType
#define SOAP_TYPE_wsdd__QNameListType (55)
typedef _QName wsdd__QNameListType;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:101 */
#ifndef SOAP_TYPE_wsdd__UriListType
#define SOAP_TYPE_wsdd__UriListType (56)
typedef char *wsdd__UriListType;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:104 */
#ifndef SOAP_TYPE_wsdd__FaultCodeOpenType
#define SOAP_TYPE_wsdd__FaultCodeOpenType (57)
typedef char *wsdd__FaultCodeOpenType;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:474 */
#ifndef SOAP_TYPE__wsdd__Hello
#define SOAP_TYPE__wsdd__Hello (64)
typedef struct wsdd__HelloType _wsdd__Hello;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:477 */
#ifndef SOAP_TYPE__wsdd__Bye
#define SOAP_TYPE__wsdd__Bye (65)
typedef struct wsdd__ByeType _wsdd__Bye;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:480 */
#ifndef SOAP_TYPE__wsdd__Probe
#define SOAP_TYPE__wsdd__Probe (66)
typedef struct wsdd__ProbeType _wsdd__Probe;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:483 */
#ifndef SOAP_TYPE__wsdd__ProbeMatches
#define SOAP_TYPE__wsdd__ProbeMatches (67)
typedef struct wsdd__ProbeMatchesType _wsdd__ProbeMatches;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:486 */
#ifndef SOAP_TYPE__wsdd__Resolve
#define SOAP_TYPE__wsdd__Resolve (68)
typedef struct wsdd__ResolveType _wsdd__Resolve;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:489 */
#ifndef SOAP_TYPE__wsdd__ResolveMatches
#define SOAP_TYPE__wsdd__ResolveMatches (69)
typedef struct wsdd__ResolveMatchesType _wsdd__ResolveMatches;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:492 */
#ifndef SOAP_TYPE__wsdd__Types
#define SOAP_TYPE__wsdd__Types (70)
typedef wsdd__QNameListType _wsdd__Types;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:495 */
#ifndef SOAP_TYPE__wsdd__Scopes
#define SOAP_TYPE__wsdd__Scopes (71)
typedef struct wsdd__ScopesType _wsdd__Scopes;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:498 */
#ifndef SOAP_TYPE__wsdd__XAddrs
#define SOAP_TYPE__wsdd__XAddrs (72)
typedef wsdd__UriListType _wsdd__XAddrs;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:501 */
#ifndef SOAP_TYPE__wsdd__MetadataVersion
#define SOAP_TYPE__wsdd__MetadataVersion (73)
typedef unsigned int _wsdd__MetadataVersion;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:504 */
#ifndef SOAP_TYPE__wsdd__SupportedMatchingRules
#define SOAP_TYPE__wsdd__SupportedMatchingRules (74)
typedef wsdd__UriListType _wsdd__SupportedMatchingRules;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:507 */
#ifndef SOAP_TYPE__wsdd__Security
#define SOAP_TYPE__wsdd__Security (75)
typedef struct wsdd__SecurityType _wsdd__Security;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:510 */
#ifndef SOAP_TYPE__wsdd__Sig
#define SOAP_TYPE__wsdd__Sig (76)
typedef struct wsdd__SigType _wsdd__Sig;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:513 */
#ifndef SOAP_TYPE__wsdd__AppSequence
#define SOAP_TYPE__wsdd__AppSequence (77)
typedef struct wsdd__AppSequenceType _wsdd__AppSequence;
#endif

/* ../../../gsoap-2.8.111/gsoap/import/wsdd10.h:524 */
#ifndef SOAP_TYPE__wsdd__Id
#define SOAP_TYPE__wsdd__Id (78)
typedef char *_wsdd__Id;
#endif

/******************************************************************************\
 *                                                                            *
 * Serializable Types                                                         *
 *                                                                            *
\******************************************************************************/


/* char has binding name 'byte' for type 'xsd:byte' */
#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif

/* int has binding name 'int' for type 'xsd:int' */
#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif

/* _wsdd__MetadataVersion has binding name '_wsdd__MetadataVersion' for type '' */
#ifndef SOAP_TYPE__wsdd__MetadataVersion
#define SOAP_TYPE__wsdd__MetadataVersion (73)
#endif

/* _wsa__ReplyAfter has binding name '_wsa__ReplyAfter' for type '' */
#ifndef SOAP_TYPE__wsa__ReplyAfter
#define SOAP_TYPE__wsa__ReplyAfter (28)
#endif

/* unsigned int has binding name 'unsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (27)
#endif

/* enum wsdd__FaultCodeType has binding name 'wsdd__FaultCodeType' for type 'wsdd:FaultCodeType' */
#ifndef SOAP_TYPE_wsdd__FaultCodeType
#define SOAP_TYPE_wsdd__FaultCodeType (58)
#endif

/* enum wsa__FaultSubcodeValues has binding name 'wsa__FaultSubcodeValues' for type 'wsa:FaultSubcodeValues' */
#ifndef SOAP_TYPE_wsa__FaultSubcodeValues
#define SOAP_TYPE_wsa__FaultSubcodeValues (13)
#endif

/* enum wsa__RelationshipTypeValues has binding name 'wsa__RelationshipTypeValues' for type 'wsa:RelationshipTypeValues' */
#ifndef SOAP_TYPE_wsa__RelationshipTypeValues
#define SOAP_TYPE_wsa__RelationshipTypeValues (12)
#endif

/* _wsdd__AppSequence has binding name '_wsdd__AppSequence' for type '' */
#ifndef SOAP_TYPE__wsdd__AppSequence
#define SOAP_TYPE__wsdd__AppSequence (77)
#endif

/* _wsdd__Sig has binding name '_wsdd__Sig' for type '' */
#ifndef SOAP_TYPE__wsdd__Sig
#define SOAP_TYPE__wsdd__Sig (76)
#endif

/* _wsdd__Security has binding name '_wsdd__Security' for type '' */
#ifndef SOAP_TYPE__wsdd__Security
#define SOAP_TYPE__wsdd__Security (75)
#endif

/* _wsdd__Scopes has binding name '_wsdd__Scopes' for type '' */
#ifndef SOAP_TYPE__wsdd__Scopes
#define SOAP_TYPE__wsdd__Scopes (71)
#endif

/* _wsdd__ResolveMatches has binding name '_wsdd__ResolveMatches' for type '' */
#ifndef SOAP_TYPE__wsdd__ResolveMatches
#define SOAP_TYPE__wsdd__ResolveMatches (69)
#endif

/* _wsdd__Resolve has binding name '_wsdd__Resolve' for type '' */
#ifndef SOAP_TYPE__wsdd__Resolve
#define SOAP_TYPE__wsdd__Resolve (68)
#endif

/* _wsdd__ProbeMatches has binding name '_wsdd__ProbeMatches' for type '' */
#ifndef SOAP_TYPE__wsdd__ProbeMatches
#define SOAP_TYPE__wsdd__ProbeMatches (67)
#endif

/* _wsdd__Probe has binding name '_wsdd__Probe' for type '' */
#ifndef SOAP_TYPE__wsdd__Probe
#define SOAP_TYPE__wsdd__Probe (66)
#endif

/* _wsdd__Bye has binding name '_wsdd__Bye' for type '' */
#ifndef SOAP_TYPE__wsdd__Bye
#define SOAP_TYPE__wsdd__Bye (65)
#endif

/* _wsdd__Hello has binding name '_wsdd__Hello' for type '' */
#ifndef SOAP_TYPE__wsdd__Hello
#define SOAP_TYPE__wsdd__Hello (64)
#endif

/* struct wsdd__AppSequenceType has binding name 'wsdd__AppSequenceType' for type 'wsdd:AppSequenceType' */
#ifndef SOAP_TYPE_wsdd__AppSequenceType
#define SOAP_TYPE_wsdd__AppSequenceType (54)
#endif

/* struct wsdd__SigType has binding name 'wsdd__SigType' for type 'wsdd:SigType' */
#ifndef SOAP_TYPE_wsdd__SigType
#define SOAP_TYPE_wsdd__SigType (53)
#endif

/* struct wsdd__SecurityType has binding name 'wsdd__SecurityType' for type 'wsdd:SecurityType' */
#ifndef SOAP_TYPE_wsdd__SecurityType
#define SOAP_TYPE_wsdd__SecurityType (52)
#endif

/* struct wsdd__ScopesType has binding name 'wsdd__ScopesType' for type 'wsdd:ScopesType' */
#ifndef SOAP_TYPE_wsdd__ScopesType
#define SOAP_TYPE_wsdd__ScopesType (51)
#endif

/* struct wsdd__ResolveMatchType has binding name 'wsdd__ResolveMatchType' for type 'wsdd:ResolveMatchType' */
#ifndef SOAP_TYPE_wsdd__ResolveMatchType
#define SOAP_TYPE_wsdd__ResolveMatchType (50)
#endif

/* struct wsdd__ResolveMatchesType has binding name 'wsdd__ResolveMatchesType' for type 'wsdd:ResolveMatchesType' */
#ifndef SOAP_TYPE_wsdd__ResolveMatchesType
#define SOAP_TYPE_wsdd__ResolveMatchesType (49)
#endif

/* struct wsdd__ResolveType has binding name 'wsdd__ResolveType' for type 'wsdd:ResolveType' */
#ifndef SOAP_TYPE_wsdd__ResolveType
#define SOAP_TYPE_wsdd__ResolveType (48)
#endif

/* struct wsdd__ProbeMatchType has binding name 'wsdd__ProbeMatchType' for type 'wsdd:ProbeMatchType' */
#ifndef SOAP_TYPE_wsdd__ProbeMatchType
#define SOAP_TYPE_wsdd__ProbeMatchType (47)
#endif

/* struct wsdd__ProbeMatchesType has binding name 'wsdd__ProbeMatchesType' for type 'wsdd:ProbeMatchesType' */
#ifndef SOAP_TYPE_wsdd__ProbeMatchesType
#define SOAP_TYPE_wsdd__ProbeMatchesType (46)
#endif

/* struct wsdd__ProbeType has binding name 'wsdd__ProbeType' for type 'wsdd:ProbeType' */
#ifndef SOAP_TYPE_wsdd__ProbeType
#define SOAP_TYPE_wsdd__ProbeType (45)
#endif

/* struct wsdd__ByeType has binding name 'wsdd__ByeType' for type 'wsdd:ByeType' */
#ifndef SOAP_TYPE_wsdd__ByeType
#define SOAP_TYPE_wsdd__ByeType (44)
#endif

/* struct wsdd__HelloType has binding name 'wsdd__HelloType' for type 'wsdd:HelloType' */
#ifndef SOAP_TYPE_wsdd__HelloType
#define SOAP_TYPE_wsdd__HelloType (43)
#endif

/* struct SOAP_ENV__Fault has binding name 'SOAP_ENV__Fault' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (42)
#endif

/* struct SOAP_ENV__Reason has binding name 'SOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (38)
#endif

/* struct SOAP_ENV__Code has binding name 'SOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (36)
#endif

/* struct SOAP_ENV__Detail has binding name 'SOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (34)
#endif

/* struct SOAP_ENV__Header has binding name 'SOAP_ENV__Header' for type '' */
#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (29)
#endif

/* _wsa__FaultTo has binding name '_wsa__FaultTo' for type '' */
#ifndef SOAP_TYPE__wsa__FaultTo
#define SOAP_TYPE__wsa__FaultTo (26)
#endif

/* _wsa__ReplyTo has binding name '_wsa__ReplyTo' for type '' */
#ifndef SOAP_TYPE__wsa__ReplyTo
#define SOAP_TYPE__wsa__ReplyTo (25)
#endif

/* _wsa__From has binding name '_wsa__From' for type '' */
#ifndef SOAP_TYPE__wsa__From
#define SOAP_TYPE__wsa__From (24)
#endif

/* _wsa__RelatesTo has binding name '_wsa__RelatesTo' for type '' */
#ifndef SOAP_TYPE__wsa__RelatesTo
#define SOAP_TYPE__wsa__RelatesTo (21)
#endif

/* _wsa__EndpointReference has binding name '_wsa__EndpointReference' for type '' */
#ifndef SOAP_TYPE__wsa__EndpointReference
#define SOAP_TYPE__wsa__EndpointReference (19)
#endif

/* struct wsa__Relationship has binding name 'wsa__Relationship' for type 'wsa:Relationship' */
#ifndef SOAP_TYPE_wsa__Relationship
#define SOAP_TYPE_wsa__Relationship (11)
#endif

/* struct wsa__ServiceNameType has binding name 'wsa__ServiceNameType' for type 'wsa:ServiceNameType' */
#ifndef SOAP_TYPE_wsa__ServiceNameType
#define SOAP_TYPE_wsa__ServiceNameType (10)
#endif

/* struct wsa__ReferenceParametersType has binding name 'wsa__ReferenceParametersType' for type 'wsa:ReferenceParametersType' */
#ifndef SOAP_TYPE_wsa__ReferenceParametersType
#define SOAP_TYPE_wsa__ReferenceParametersType (9)
#endif

/* struct wsa__ReferencePropertiesType has binding name 'wsa__ReferencePropertiesType' for type 'wsa:ReferencePropertiesType' */
#ifndef SOAP_TYPE_wsa__ReferencePropertiesType
#define SOAP_TYPE_wsa__ReferencePropertiesType (8)
#endif

/* struct wsa__EndpointReferenceType has binding name 'wsa__EndpointReferenceType' for type 'wsa:EndpointReferenceType' */
#ifndef SOAP_TYPE_wsa__EndpointReferenceType
#define SOAP_TYPE_wsa__EndpointReferenceType (7)
#endif

/* struct wsdd__ResolveMatchesType * has binding name 'PointerTowsdd__ResolveMatchesType' for type 'wsdd:ResolveMatchesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveMatchesType
#define SOAP_TYPE_PointerTowsdd__ResolveMatchesType (95)
#endif

/* struct wsdd__ResolveType * has binding name 'PointerTowsdd__ResolveType' for type 'wsdd:ResolveType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveType
#define SOAP_TYPE_PointerTowsdd__ResolveType (92)
#endif

/* struct wsdd__ProbeMatchesType * has binding name 'PointerTowsdd__ProbeMatchesType' for type 'wsdd:ProbeMatchesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeMatchesType
#define SOAP_TYPE_PointerTowsdd__ProbeMatchesType (89)
#endif

/* struct wsdd__ProbeType * has binding name 'PointerTowsdd__ProbeType' for type 'wsdd:ProbeType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeType
#define SOAP_TYPE_PointerTowsdd__ProbeType (86)
#endif

/* struct wsdd__ByeType * has binding name 'PointerTowsdd__ByeType' for type 'wsdd:ByeType' */
#ifndef SOAP_TYPE_PointerTowsdd__ByeType
#define SOAP_TYPE_PointerTowsdd__ByeType (83)
#endif

/* struct wsdd__HelloType * has binding name 'PointerTowsdd__HelloType' for type 'wsdd:HelloType' */
#ifndef SOAP_TYPE_PointerTowsdd__HelloType
#define SOAP_TYPE_PointerTowsdd__HelloType (80)
#endif

/* struct wsdd__AppSequenceType * has binding name 'PointerTowsdd__AppSequenceType' for type 'wsdd:AppSequenceType' */
#ifndef SOAP_TYPE_PointerTowsdd__AppSequenceType
#define SOAP_TYPE_PointerTowsdd__AppSequenceType (79)
#endif

/* _wsdd__Id has binding name '_wsdd__Id' for type '' */
#ifndef SOAP_TYPE__wsdd__Id
#define SOAP_TYPE__wsdd__Id (78)
#endif

/* _wsdd__SupportedMatchingRules has binding name '_wsdd__SupportedMatchingRules' for type '' */
#ifndef SOAP_TYPE__wsdd__SupportedMatchingRules
#define SOAP_TYPE__wsdd__SupportedMatchingRules (74)
#endif

/* _wsdd__XAddrs has binding name '_wsdd__XAddrs' for type '' */
#ifndef SOAP_TYPE__wsdd__XAddrs
#define SOAP_TYPE__wsdd__XAddrs (72)
#endif

/* _wsdd__Types has binding name '_wsdd__Types' for type 'xsd:QName' */
#ifndef SOAP_TYPE__wsdd__Types
#define SOAP_TYPE__wsdd__Types (70)
#endif

/* struct wsdd__SigType * has binding name 'PointerTowsdd__SigType' for type 'wsdd:SigType' */
#ifndef SOAP_TYPE_PointerTowsdd__SigType
#define SOAP_TYPE_PointerTowsdd__SigType (63)
#endif

/* struct wsdd__ResolveMatchType * has binding name 'PointerTowsdd__ResolveMatchType' for type 'wsdd:ResolveMatchType' */
#ifndef SOAP_TYPE_PointerTowsdd__ResolveMatchType
#define SOAP_TYPE_PointerTowsdd__ResolveMatchType (62)
#endif

/* struct wsdd__ProbeMatchType * has binding name 'PointerTowsdd__ProbeMatchType' for type 'wsdd:ProbeMatchType' */
#ifndef SOAP_TYPE_PointerTowsdd__ProbeMatchType
#define SOAP_TYPE_PointerTowsdd__ProbeMatchType (61)
#endif

/* unsigned int * has binding name 'PointerTounsignedInt' for type 'xsd:unsignedInt' */
#ifndef SOAP_TYPE_PointerTounsignedInt
#define SOAP_TYPE_PointerTounsignedInt (60)
#endif

/* struct wsdd__ScopesType * has binding name 'PointerTowsdd__ScopesType' for type 'wsdd:ScopesType' */
#ifndef SOAP_TYPE_PointerTowsdd__ScopesType
#define SOAP_TYPE_PointerTowsdd__ScopesType (59)
#endif

/* wsdd__FaultCodeOpenType has binding name 'wsdd__FaultCodeOpenType' for type 'wsdd:FaultCodeOpenType' */
#ifndef SOAP_TYPE_wsdd__FaultCodeOpenType
#define SOAP_TYPE_wsdd__FaultCodeOpenType (57)
#endif

/* wsdd__UriListType has binding name 'wsdd__UriListType' for type 'wsdd:UriListType' */
#ifndef SOAP_TYPE_wsdd__UriListType
#define SOAP_TYPE_wsdd__UriListType (56)
#endif

/* wsdd__QNameListType has binding name 'wsdd__QNameListType' for type 'xsd:QName' */
#ifndef SOAP_TYPE_wsdd__QNameListType
#define SOAP_TYPE_wsdd__QNameListType (55)
#endif

/* struct SOAP_ENV__Reason * has binding name 'PointerToSOAP_ENV__Reason' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (39)
#endif

/* struct SOAP_ENV__Code * has binding name 'PointerToSOAP_ENV__Code' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (37)
#endif

/* struct SOAP_ENV__Detail * has binding name 'PointerToSOAP_ENV__Detail' for type '' */
#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (35)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__FaultTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__FaultTo
#define SOAP_TYPE_PointerTo_wsa__FaultTo (33)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__ReplyTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__ReplyTo
#define SOAP_TYPE_PointerTo_wsa__ReplyTo (32)
#endif

/* struct wsa__EndpointReferenceType * has binding name 'PointerTo_wsa__From' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__From
#define SOAP_TYPE_PointerTo_wsa__From (31)
#endif

/* struct wsa__Relationship * has binding name 'PointerTo_wsa__RelatesTo' for type '' */
#ifndef SOAP_TYPE_PointerTo_wsa__RelatesTo
#define SOAP_TYPE_PointerTo_wsa__RelatesTo (30)
#endif

/* _wsa__Action has binding name '_wsa__Action' for type '' */
#ifndef SOAP_TYPE__wsa__Action
#define SOAP_TYPE__wsa__Action (23)
#endif

/* _wsa__To has binding name '_wsa__To' for type '' */
#ifndef SOAP_TYPE__wsa__To
#define SOAP_TYPE__wsa__To (22)
#endif

/* _wsa__MessageID has binding name '_wsa__MessageID' for type '' */
#ifndef SOAP_TYPE__wsa__MessageID
#define SOAP_TYPE__wsa__MessageID (20)
#endif

/* char ** has binding name 'PointerTo_XML' for type '' */
#ifndef SOAP_TYPE_PointerTo_XML
#define SOAP_TYPE_PointerTo_XML (18)
#endif

/* struct wsa__ServiceNameType * has binding name 'PointerTowsa__ServiceNameType' for type 'wsa:ServiceNameType' */
#ifndef SOAP_TYPE_PointerTowsa__ServiceNameType
#define SOAP_TYPE_PointerTowsa__ServiceNameType (17)
#endif

/* char ** has binding name 'PointerTo_QName' for type '' */
#ifndef SOAP_TYPE_PointerTo_QName
#define SOAP_TYPE_PointerTo_QName (16)
#endif

/* struct wsa__ReferenceParametersType * has binding name 'PointerTowsa__ReferenceParametersType' for type 'wsa:ReferenceParametersType' */
#ifndef SOAP_TYPE_PointerTowsa__ReferenceParametersType
#define SOAP_TYPE_PointerTowsa__ReferenceParametersType (15)
#endif

/* struct wsa__ReferencePropertiesType * has binding name 'PointerTowsa__ReferencePropertiesType' for type 'wsa:ReferencePropertiesType' */
#ifndef SOAP_TYPE_PointerTowsa__ReferencePropertiesType
#define SOAP_TYPE_PointerTowsa__ReferencePropertiesType (14)
#endif

/* _QName has binding name '_QName' for type 'xsd:QName' */
#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (6)
#endif

/* _XML has binding name '_XML' for type '' */
#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (5)
#endif

/* char * has binding name 'string' for type 'xsd:string' */
#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif

/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


#endif

/* End of onvifdiscoveryStub.h */
